// export { AuthService } from './auth.service';
// export { CategoryService } from './category.service';
// export { ChatService } from './chat.service';
// export { DatasService } from './datas.service';
// export { DeviceService } from './device.service';
// export { DiagnosisService } from './diagnosis.service';
// export { FollowupsService } from './followups.service';
// export { ImageItemsService } from './image-items.service';
// export { ImagesService } from './images.service';
// export { InvoiceService } from './invoice.service';
// export { LabItemsService } from './lab-items.service';
// export { LabsService } from './labs.service';
// export { LoadPatientService } from './load-patient.service';
// export { MailService } from './mails.service';
// export { MedicalHistoryService } from './medical-history.service';
// export { MedsService } from './meds.service';
// export { NoteService } from './notes.service';
// export { OrderItemsService } from './order-items.service';
// export { OrdersService } from './orders.service';
// export { PathwayService } from './pathway.service';
// export { PaymentService } from './payment.service';
// export { ProblemService } from './problems.service';
// export { ReportsService } from './reports.service';
// export { FormService } from './save-forms.service';
// export { ScreeningService } from './screenings.service';
// export { SetFormsService } from './set-forms.service';
// export { SharedDataService } from './shared-data.service';
// export { SharedPageTypeService } from './shared-page-type.service';
// export { SharedRoleService } from './shared-role.service';
// export { ShareProviderService } from './share-provider.service';
// export { UploadService } from './upload.service';
// export { UsersService } from './users.service';
// export { VisitsService } from './visits.service';
// export { HttpService } from './http.service';
// export { UtilService } from './util.service';
export { AllServices } from './all-services';
export { WechatJssdkConfig } from './wx-services/wechat-jssdk/wechat-jssdk-config';
export { WeixinJsapiConfig } from './wx-services/weixin-jsapi/weixin-jsapi-config'
